# Generated by Django 5.2.15 on 2026-07-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='commissionsettlement',
            new_name='payments_co_worker__387f08_idx',
            old_name='payments_settle_worker_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionsettlement',
            new_name='payments_co_period__2b8502_idx',
            old_name='payments_settle_period_idx',
        ),
        migrations.RenameIndex(
            model_name='commissionsettlement',
            new_name='payments_co_status_50cc8b_idx',
            old_name='payments_settle_due_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_parent__f894c0_idx',
            old_name='payments_parent_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_worker__404716_idx',
            old_name='payments_worker_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_method_c0b72b_idx',
            old_name='payments_method_status_idx',
        ),
        migrations.RenameIndex(
            model_name='payment',
            new_name='payments_pa_momo_or_fa47a9_idx',
            old_name='payments_momo_order_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlog',
            new_name='payments_pa_payment_ef6883_idx',
            old_name='payments_log_payment_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlog',
            new_name='payments_pa_settlem_9011c6_idx',
            old_name='payments_log_settle_idx',
        ),
        migrations.RenameIndex(
            model_name='paymentlog',
            new_name='payments_pa_event_t_209922_idx',
            old_name='payments_log_event_idx',
        ),
        migrations.AddField(
            model_name='payment',
            name='payos_account_reference',
            field=models.CharField(blank=True, help_text='Mã tham chiếu tài khoản — thường là STK phụ huynh dùng để chuyển', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payos_checkout_url',
            field=models.URLField(blank=True, help_text='checkoutUrl PayOS — phụ huynh mở link này để quét QR', max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payos_order_code',
            field=models.BigIntegerField(blank=True, help_text='orderCode PayOS — thường là task.id hoặc timestamp', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payos_payment_link_id',
            field=models.CharField(blank=True, help_text='ID của payment link PayOS', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='payos_status',
            field=models.CharField(blank=True, help_text='Trạng thái từ PayOS: PENDING, PAID, CANCELLED, EXPIRED', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=0.2, help_text='Tỷ lệ hoa hồng — mặc định 20%', max_digits=5),
        ),
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('momo_escrow', 'MoMo Escrow — Phụ huynh trả qua MoMo, tiền được giữ'), ('payos', 'PayOS — Phụ huynh quét QR VietQR qua app ngân hàng, tiền được giữ'), ('cash', 'Tiền mặt — Phụ huynh trả trực tiếp cho Carepartner')], max_length=20),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ thanh toán — Phụ huynh chưa hoàn tất bước pay (momo/payos) hoặc chưa chốt phương thức (cash)'), ('held', 'Đang giữ tiền — MoMo/PayOS đã nhận tiền, chờ Task hoàn thành để giải ngân'), ('completed', 'Đã hoàn tất — Đã giải ngân cho Carepartner và giữ hoa hồng'), ('cancelled', 'Đã huỷ — Task bị huỷ trước khi thanh toán'), ('refunded', 'Đã hoàn tiền — Hoàn 100% cho phụ huynh do Task bị huỷ'), ('payout_failed', 'Giải ngân thất bại — Tiền vẫn nằm trong MoMo/PayOS, cần Admin xử lý')], default='pending', max_length=20),
        ),
    ]
