# Generated by Django 5.2.15 on 2026-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_add_payos_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payos_expires_at',
            field=models.DateTimeField(blank=True, help_text='Hạn QR PayOS (expired_at trả về khi tạo link) — expiry job dùng để rollback đúng giờ', null=True),
        ),
        migrations.AlterField(
            model_name='paymentlog',
            name='event_type',
            field=models.CharField(choices=[('payment_created', 'Tạo bản ghi thanh toán'), ('momo_pay_url_generated', 'Sinh payUrl MoMo thành công'), ('momo_pay_url_failed', 'Sinh payUrl MoMo thất bại'), ('momo_ipn_held', 'MoMo IPN: tiền đã được giữ'), ('momo_ipn_failed', 'MoMo IPN: phụ huynh thanh toán thất bại'), ('escrow_released', 'Giải ngân escrow cho Carepartner thành công'), ('escrow_release_failed', 'Giải ngân escrow thất bại'), ('refund_initiated', 'Bắt đầu hoàn tiền'), ('refund_completed', 'Hoàn tiền thành công'), ('refund_failed', 'Hoàn tiền thất bại'), ('cash_recorded', 'Ghi nhận hoa hồng tiền mặt'), ('settlement_created', 'Tạo kỳ thanh toán tháng'), ('settlement_qr_generated', 'Sinh QR cho kỳ thanh toán'), ('settlement_qr_failed', 'Sinh QR thất bại'), ('settlement_paid', 'Carepartner đã thanh toán kỳ hoa hồng'), ('settlement_overdue', 'Kỳ thanh toán quá hạn'), ('settlement_reminder_sent', 'Gửi nhắc nhở kỳ thanh toán'), ('manual_override', 'Admin chỉnh sửa thủ công'), ('payos_link_created', 'Tạo payment link PayOS'), ('payos_payment_held', 'PayOS: phụ huynh đã chuyển khoản — tiền được giữ'), ('payos_payment_cancelled', 'PayOS: payment link bị huỷ'), ('payos_amount_mismatch', 'PayOS: số tiền webhook KHÁCH với payment.amount — chặn xác nhận'), ('booking_confirmed_after_payment', 'Xác nhận đặt lịch sau khi PayOS PAID'), ('vietqr_selection_expired', 'QR VietQR hết hạn — rollback về open/pending'), ('selection_cancelled', 'Phụ huynh huỷ chọn CarePartner khi đang xem QR')], max_length=40),
        ),
    ]
