# Generated by Django 6.0.4 on 2026-05-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id_card_back',
            field=models.ImageField(blank=True, help_text='Ảnh mặt sau CCCD', null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='id_card_front',
            field=models.ImageField(blank=True, help_text='Ảnh mặt trước CCCD', null=True, upload_to='id_cards/'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin duyệt tài khoản Carepartner'),
        ),
        migrations.AddField(
            model_name='user',
            name='selfie_photo',
            field=models.ImageField(blank=True, help_text='Ảnh chân dung', null=True, upload_to='selfies/'),
        ),
    ]
