# Generated by Django 6.0.4 on 2026-05-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_id_card_back_user_id_card_front_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='certificate_photo',
            field=models.ImageField(blank=True, help_text='Ảnh bằng cấp/chứng chỉ', null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='qualifications',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách bằng cấp do admin nhập sau khi duyệt'),
        ),
    ]
