# Generated by Django 6.0.4 on 2026-05-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_certificate_photo_user_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expo_push_token',
            field=models.CharField(blank=True, help_text='Expo Push Token cho thông báo', max_length=255, null=True),
        ),
    ]
