# Generated by Django 5.2.15 on 2026-06-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_parent_auto_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_login',
            field=models.BooleanField(default=True, help_text='Đánh dấu chưa xem hướng dẫn sử dụng'),
        ),
    ]
