# Generated by Django 5.2 on 2026-06-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_profilechangerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='read_by',
            field=models.JSONField(blank=True, default=list, help_text='Danh sách user ID đã đọc thông báo chung (recipient=null)'),
        ),
    ]
