# Generated by Django 6.0.6 on 2026-06-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_add_latitude_longitude_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
