# Generated by Django 5.2.15 on 2026-06-15 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_review_comment_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email / Mật khẩu'), ('google', 'Google'), ('facebook', 'Facebook')], default='email', help_text='Phương thức đăng ký/đăng nhập', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, help_text='URL ảnh đại diện từ Google/Facebook', max_length=500, null=True),
        ),
    ]
