# Generated by Django 5.2.15 on 2026-07-09 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_geofence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='geofence_radius',
            field=models.FloatField(blank=True, default=500, help_text='Bán kính vùng an toàn (mét). Mặc định 500m', null=True),
        ),
    ]
