# Generated by Django 5.2.15 on 2026-06-27 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_geofence_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='geofence_radius',
            field=models.FloatField(blank=True, default=500, help_text='Bán kính vùng an toàn (mét). Mặc định 500m', null=True),
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="Khóa cấu hình, VD: 'keepalive_enabled'", max_length=100, unique=True)),
                ('value', models.TextField(help_text='Giá trị cấu hình (lưu dưới dạng text, có thể parse sang JSON/bool/int)')),
                ('description', models.TextField(blank=True, help_text='Mô tả ý nghĩa của cấu hình này')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Thời gian cập nhật cuối cùng')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Admin cập nhật gần nhất', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cấu hình hệ thống',
                'verbose_name_plural': 'Cấu hình hệ thống',
                'ordering': ['key'],
            },
        ),
    ]
