# Generated by Django 5.2.15 on 2026-08-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_geofence_radius'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verification_pin_hash',
            field=models.CharField(blank=True, help_text='Hash mã cá nhân xác minh — KHÔNG lưu plaintext', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='verification_pin_set_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
