# Generated by Django 5.2.15 on 2026-08-22 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_verification_pin_hash_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_type', models.CharField(choices=[('distance', 'Theo khoảng cách (km)'), ('hourly', 'Theo thời lượng (giờ)'), ('fixed', 'Cố định / Thoả thuận')], default='fixed', max_length=20)),
                ('base_fee', models.DecimalField(decimal_places=0, default=0, help_text='Phí mở đầu (VNĐ)', max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, help_text='Đơn giá mỗi km hoặc mỗi giờ (VNĐ)', max_digits=10)),
                ('min_price', models.DecimalField(decimal_places=0, default=0, help_text='Giá tối thiểu trong khoảng gợi ý (VNĐ)', max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=0, default=0, help_text='Giá tối đa trong khoảng gợi ý (VNĐ)', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.OneToOneField(help_text='Mỗi danh mục chỉ có 1 quy tắc giá', on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rule', to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Quy tắc giá gợi ý',
                'verbose_name_plural': 'Quy tắc giá gợi ý',
            },
        ),
    ]
