# Generated by Django 5.2.15 on 2026-08-22 03:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_add_pricing_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Thứ Hai'), (1, 'Thứ Ba'), (2, 'Thứ Tư'), (3, 'Thứ Năm'), (4, 'Thứ Sáu'), (5, 'Thứ Bảy'), (6, 'Chủ Nhật')], help_text='Thứ trong tuần (0=Thứ Hai, 6=Chủ Nhật)')),
                ('start_time', models.TimeField(help_text='Giờ bắt đầu (VD: 14:00)')),
                ('end_time', models.TimeField(help_text='Giờ kết thúc (VD: 18:00)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(help_text='CarePartner sở hữu khung giờ này', on_delete=django.db.models.deletion.CASCADE, related_name='availability_windows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Khung giờ rảnh',
                'verbose_name_plural': 'Khung giờ rảnh',
                'indexes': [models.Index(fields=['worker', 'weekday'], name='idx_worker_weekday')],
                'constraints': [models.UniqueConstraint(fields=('worker', 'weekday', 'start_time', 'end_time'), name='unique_availability_window')],
            },
        ),
    ]
