# Generated by Django 5.2.15 on 2026-08-22 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_tier_and_credential_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilechangerequest',
            name='proposed_changes',
            field=models.JSONField(help_text='Dữ liệu thay đổi yêu cầu'),
        ),
        migrations.AlterField(
            model_name='task',
            name='geofence_lat',
            field=models.FloatField(blank=True, help_text='Vĩ độ tâm vùng an toàn (geofence)', null=True),
        ),
    ]
