# Generated by Django 5.2.15 on 2026-08-22 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_add_worker_availability'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='workeravailability',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__lt', models.F('end_time'))), name='check_start_before_end', violation_error_message='Giờ kết thúc phải sau giờ bắt đầu.'),
        ),
    ]
