# Generated by Django 5.2.15 on 2026-08-23 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_user_tier_and_credential_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="N: thời điểm task chuyển 'completed' (chat đóng tại completed_at + 24h).", null=True),
        ),
    ]
