# Generated by Django 5.2.15 on 2026-09-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_landing_survey_signup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landingsurvey',
            name='interests',
        ),
        migrations.RemoveField(
            model_name='landingsurvey',
            name='necessity',
        ),
        migrations.AddField(
            model_name='landingsurvey',
            name='role_answers',
            field=models.JSONField(blank=True, default=dict, help_text='Bộ câu hỏi riêng theo role (carepartner/phu-huynh)'),
        ),
        migrations.AlterField(
            model_name='landingsurvey',
            name='feedback',
            field=models.TextField(blank=True, default='', help_text='Góp ý tự do (common cho cả 2 role)'),
        ),
        migrations.AlterField(
            model_name='landingsurvey',
            name='role',
            field=models.CharField(choices=[('carepartner', 'Người đồng hành (CarePartner)'), ('phu-huynh', 'Phụ huynh')], max_length=20),
        ),
        migrations.CreateModel(
            name='LandingPageVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='Frontend-generated UUID, 1 per browser session', max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('referrer', models.URLField(blank=True, default='')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lượt truy cập landing',
                'verbose_name_plural': 'Lượt truy cập landing',
                'ordering': ['-visited_at'],
                'indexes': [models.Index(fields=['-visited_at'], name='idx_visit_visited_at')],
            },
        ),
    ]
