# Generated by Django 5.2.15 on 2026-09-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_landing_page_visit_and_survey_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicecategory',
            name='is_active',
            field=models.BooleanField(default=True, help_text='False = danh mục bị khóa, không hiển thị và không cho đăng việc mới'),
        ),
    ]
