# Generated by Django 5.2.15 on 2026-09-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_lock_legacy_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsignup',
            name='interested_service',
            field=models.CharField(blank=True, choices=[('tutoring', 'Gia sư học tập'), ('pickup', 'Đưa đón bé tan học'), ('childcare', 'Trông trẻ tại nhà'), ('chua-ro', 'Chưa rõ — cần tư vấn thêm')], default='', help_text='Dịch vụ quan tâm nhất (phân khúc thị trường — bổ sung 2026-09-11)', max_length=20),
        ),
        migrations.AddField(
            model_name='landingsignup',
            name='location_city',
            field=models.CharField(blank=True, choices=[('Hà Nội', 'Hà Nội'), ('TP. Hồ Chí Minh', 'TP. Hồ Chí Minh'), ('Đà Nẵng', 'Đà Nẵng'), ('Tỉnh thành khác', 'Tỉnh thành khác')], default='', help_text='Tỉnh/Thành phố của bạn (địa bàn phủ sóng)', max_length=50),
        ),
        migrations.AddField(
            model_name='landingsignup',
            name='location_district',
            field=models.CharField(blank=True, default='', help_text='Quận/Huyện (VD: Cầu Giấy, Quận 7, TP. Thủ Đức...)', max_length=100),
        ),
        migrations.AlterField(
            model_name='landingsignup',
            name='preferred_time_slot',
            field=models.CharField(blank=True, choices=[('sang', 'Sáng (08:30 – 11:30)'), ('chieu', 'Chiều (13:30 – 17:00)'), ('toi', 'Tối (18:30 – 20:30)')], default='', help_text='Khung giờ gọi lại (chỉ cho tư vấn)', max_length=10),
        ),
    ]
