# Generated by Django 5.2.15 on 2026-09-12 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_landingsignup_interested_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsurvey',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Số điện thoại người góp ý', max_length=30),
        ),
        migrations.AlterField(
            model_name='landingsurvey',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Email người góp ý', max_length=254),
        ),
    ]
