# Generated by Django 5.2.15 on 2026-09-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_landingsurvey_phone_alter_landingsurvey_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_latitude',
            field=models.FloatField(blank=True, help_text='Vĩ độ GPS real-time lần cuối (nullable — chưa từng sync thì None)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='current_longitude',
            field=models.FloatField(blank=True, help_text='Kinh độ GPS real-time lần cuối (nullable — chưa từng sync thì None)', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_gps_updated_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Thời điểm GPS real-time được cập nhật lần cuối', null=True),
        ),
    ]
