# Generated by Django 5.2.15 on 2026-09-13 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_user_current_latitude_user_current_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='matching_gps_consent',
            field=models.BooleanField(default=False, help_text='CarePartner cho phép dùng vị trí để gợi ý việc gần bạn (consent matching-GPS, tách khỏi live-tracking trong ca)'),
        ),
    ]
