# Generated by Django 5.2.15 on 2026-09-14 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_matching_gps_consent'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingsurvey',
            name='full_name',
            field=models.CharField(blank=True, default='', help_text='Họ và tên người góp ý (bắt buộc với submit mới từ 2026-09-14; bản ghi cũ trước khi có field sẽ để trống)', max_length=200),
        ),
    ]
