# Generated by Django 5.2.15 on 2026-09-16 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_fill_survey_names_seed_trial_signups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('open', 'Đang tìm người'), ('pending_payment', 'Chờ thanh toán để xác nhận'), ('in_progress', 'Đang thực hiện'), ('completed', 'Đã hoàn thành'), ('cancelled', 'Đã hủy')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='taskapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('payment_pending', 'Đã chọn — chờ thanh toán'), ('accepted', 'Đã được chọn'), ('rejected', 'Bị từ chối')], default='pending', max_length=20),
        ),
    ]
