# Generated by Django 5.2.15 on 2026-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_servicecategory_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingsignup',
            name='interested_service',
            field=models.CharField(blank=True, choices=[('tutoring', 'Gia sư học tập'), ('pickup', 'Đưa đón bé tan học'), ('childcare', 'Đồng hành cùng trẻ tại nhà'), ('chua-ro', 'Chưa rõ — cần tư vấn thêm')], default='', help_text='Dịch vụ quan tâm nhất (phân khúc thị trường — bổ sung 2026-09-11)', max_length=20),
        ),
    ]
