# Generated by Django 5.2.15 on 2026-08-23 10:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0020_task_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opens_at', models.DateTimeField(help_text='Thời điểm cửa sổ chat mở (task → in_progress)')),
                ('closes_at', models.DateTimeField(blank=True, help_text='Hạn chót đóng cửa sổ (completed_at + 24h). NULL = task chưa kết thúc.', null=True)),
                ('status', models.CharField(choices=[('open', 'Đang mở — có thể gửi tin nhắn'), ('closed', 'Đã đóng — chỉ xem lại lịch sử (read-only)')], db_index=True, default='open', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_parent', to=settings.AUTH_USER_MODEL)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conversation', to='core.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_as_worker', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cuộc trò chuyện',
                'verbose_name_plural': 'Cuộc trò chuyện',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Nội dung tin nhắn (đã qua kiểm duyệt từ khoá cấm)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='Thời điểm người nhận đọc (NULL = chưa đọc).', null=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_messages_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tin nhắn chat',
                'verbose_name_plural': 'Tin nhắn chat',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['status', 'closes_at'], name='chat_conver_status_de06e7_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['parent', 'status'], name='chat_conver_parent__dd6347_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['worker', 'status'], name='chat_conver_worker__acefc8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'id'], name='chat_messag_convers_0a488e_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'read_at'], name='chat_messag_convers_cc093a_idx'),
        ),
    ]
