# Generated by Django 5.2.15 on 2026-08-22 11:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0018_add_availability_check_constraint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareDiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood_icon', models.CharField(blank=True, default='', max_length=30)),
                ('mood_label', models.CharField(blank=True, default='', max_length=100)),
                ('mood_note', models.TextField(blank=True, default='')),
                ('completion_percent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='care_diary', to='core.task')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='care_diary_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhật ký chăm sóc',
                'verbose_name_plural': 'Nhật ký chăm sóc',
            },
        ),
        migrations.CreateModel(
            name='CareDiaryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='care_diary_attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='care_diary.carediaryentry')),
            ],
            options={
                'verbose_name': 'Ảnh đính kèm nhật ký',
                'verbose_name_plural': 'Ảnh đính kèm nhật ký',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CareDiaryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('done', 'Hoàn thành'), ('partial', 'Một phần'), ('skipped', 'Bỏ qua')], default='done', max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='care_diary.carediaryentry')),
            ],
            options={
                'verbose_name': 'Hoạt động nhật ký',
                'verbose_name_plural': 'Hoạt động nhật ký',
                'ordering': ['order', 'id'],
            },
        ),
    ]
