# Generated by Django 5.2.15 on 2026-09-18 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carediaryentry',
            name='assessment_data',
            field=models.JSONField(blank=True, default=dict, help_text='Nội dung form chuyên sâu (schema theo assessment_type, có key schema_version).'),
        ),
        migrations.AddField(
            model_name='carediaryentry',
            name='assessment_type',
            field=models.CharField(choices=[('tutoring', 'Gia sư'), ('childcare', 'Trông trẻ'), ('general', 'Chung')], db_index=True, default='general', help_text='Loại form đánh giá — quyết định card hiển thị ở phía phụ huynh.', max_length=20),
        ),
    ]
