# Generated by Django 5.2.15 on 2026-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_diary', '0002_carediaryentry_assessment_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carediaryentry',
            name='assessment_type',
            field=models.CharField(choices=[('tutoring', 'Gia sư'), ('childcare', 'Đồng hành cùng trẻ'), ('general', 'Chung')], db_index=True, default='general', help_text='Loại form đánh giá — quyết định card hiển thị ở phía phụ huynh.', max_length=20),
        ),
    ]
