# Generated by Django 5.2.15 on 2026-07-22 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_geofence_radius'),
        ('moderation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='taskmoderation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='moderation__status_90b5ae_idx',
            old_name='moderation_status_pri_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='moderation__complai_55a287_idx',
            old_name='moderation_complain_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='moderation__reporte_133298_idx',
            old_name='moderation_reported_idx',
        ),
        migrations.RenameIndex(
            model_name='taskmoderation',
            new_name='moderation__status_f84d85_idx',
            old_name='moderation_status_idx',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='admin_response',
            field=models.TextField(blank=True, default='', help_text='Phản hồi admin cho carepartner'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ai_analysis',
            field=models.TextField(blank=True, default='', help_text='AI tóm tắt + phân loại'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ai_priority',
            field=models.CharField(choices=[('low', 'Thấp'), ('medium', 'Trung bình'), ('high', 'Cao'), ('urgent', 'Khẩn cấp')], default='medium', help_text='AI đề xuất mức ưu tiên', max_length=10),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='ai_suggestion',
            field=models.TextField(blank=True, default='', help_text='AI gợi ý hành động cho admin'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complainant',
            field=models.ForeignKey(help_text='Carepartner gửi khiếu nại', on_delete=django.db.models.deletion.CASCADE, related_name='filed_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='description',
            field=models.TextField(help_text='Mô tả chi tiết sự việc'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='reported_user',
            field=models.ForeignKey(help_text='Phụ huynh bị khiếu nại', on_delete=django.db.models.deletion.CASCADE, related_name='received_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='task',
            field=models.ForeignKey(blank=True, help_text='Task liên quan (nếu có)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaints', to='core.task'),
        ),
        migrations.AlterField(
            model_name='complaintevidence',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Mô tả bằng chứng'),
        ),
        migrations.AlterField(
            model_name='complaintevidence',
            name='file',
            field=models.FileField(help_text='File ảnh/video/văn bản', upload_to='complaint_evidence/'),
        ),
        migrations.AlterField(
            model_name='taskmoderation',
            name='admin_note',
            field=models.TextField(blank=True, default='', help_text='Ghi chú admin khi override'),
        ),
        migrations.AlterField(
            model_name='taskmoderation',
            name='ai_confidence',
            field=models.FloatField(default=0, help_text='Độ tin cậy 0-1'),
        ),
        migrations.AlterField(
            model_name='taskmoderation',
            name='ai_flags',
            field=models.JSONField(blank=True, default=list, help_text="Các cờ vi phạm: ['chinh_tri', 'bao_luc', 'lua_dao', ...]"),
        ),
        migrations.AlterField(
            model_name='taskmoderation',
            name='ai_suggestion',
            field=models.TextField(blank=True, default='', help_text='Gợi ý AI cho admin nếu needs_review'),
        ),
        migrations.AlterField(
            model_name='taskmoderation',
            name='ai_verdict',
            field=models.TextField(blank=True, default='', help_text='AI đánh giá chi tiết'),
        ),
    ]
