# Generated by Django 5.2.15 on 2026-09-08 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carepartnerprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Nam'), ('female', 'Nữ')], default='', help_text='Hard filter #5 (flow1-step2-matching-engine.md dòng 57): parent yêu cầu giới tính cụ thể → CP khác giới bị loại trước khi chấm điểm. Giá trị khớp chuẩn đã normalize ở gemini_service (male/female). Bỏ trống = chưa khai báo → KHÔNG chặn ghép cặp (newcomer-friendly, không auto-reject). Chỉ áp dụng childcare/pickup — tutoring luôn bỏ qua (Step 11.4).', max_length=10),
        ),
    ]
