# Generated by Django 5.2.15 on 2026-09-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_carepartnerprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtemplate',
            name='code',
            field=models.CharField(choices=[('job_assigned', 'carepartner'), ('booking_committed', 'carepartner'), ('booking_committed_parent', 'parent'), ('commit_expired', 'parent'), ('carepartner_declined', 'parent'), ('carepartner_cancelled', 'parent'), ('carepartner_no_show', 'parent'), ('replacement_found', 'parent'), ('no_replacement', 'parent'), ('compensation_issued', 'parent'), ('job_reminder_60m', 'both'), ('reschedule_requested', 'parent'), ('reschedule_answer_needed', 'parent'), ('review_requested', 'both'), ('elo_band_changed', 'carepartner'), ('account_suspended', 'carepartner'), ('appeal_decided', 'carepartner'), ('blackout_paused', 'carepartner')], max_length=40, unique=True),
        ),
    ]
