# Generated by Django 5.2.15 on 2026-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_alter_notificationtemplate_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(choices=[('tutoring', 'Gia sư'), ('childcare', 'Đồng hành cùng trẻ'), ('pickup', 'Đón trẻ')], db_index=True, help_text='Chỉ 3 loại — parent chọn tường minh, AI không được đè', max_length=20),
        ),
    ]
