# Generated by Django 5.2.15 on 2026-07-09 17:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_task_geofence_radius'),
        ('tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(db_index=True, help_text='Lần cuối carepartner gửi heartbeat')),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Vị trí GPS lần cuối (để parent biết carepartner ở đâu khi mất kết nối)', max_digits=10, null=True)),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('device_status', models.CharField(choices=[('online', 'Trực tuyến — đang gửi heartbeat'), ('offline', 'Ngoại tuyến — không nhận heartbeat > 90s'), ('stopped', 'Đã dừng — task hoàn thành/huỷ')], db_index=True, default='online', max_length=20)),
                ('battery_level', models.IntegerField(blank=True, help_text='% pin (0-100)', null=True)),
                ('app_state', models.CharField(blank=True, default='', help_text='foreground/background/killed', max_length=20)),
                ('network_type', models.CharField(blank=True, default='', help_text='wifi/cellular/none', max_length=20)),
                ('offline_detected_at', models.DateTimeField(blank=True, help_text='Khi phát hiện offline', null=True)),
                ('offline_alert_sent', models.BooleanField(default=False, help_text='Đã gửi push cho phụ huynh chưa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceOfflineAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_seen', models.DateTimeField(help_text='Lần cuối carepartner gửi heartbeat trước khi mất kết nối')),
                ('last_location_lat', models.DecimalField(blank=True, decimal_places=7, help_text='Vị trí GPS cuối cùng biết', max_digits=10, null=True)),
                ('last_location_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Đang khẩn cấp — thiết bị vẫn offline'), ('recovered', 'Thiết bị đã online trở lại'), ('task_ended', 'Task đã kết thúc (completed/cancelled)'), ('false', 'Báo động sai (lỗi mạng backend)')], db_index=True, default='active', max_length=20)),
                ('push_sent', models.BooleanField(default=False, help_text='Đã gửi push cho phụ huynh')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True)),
                ('recovered_at', models.DateTimeField(blank=True, null=True)),
                ('recovery_duration_seconds', models.IntegerField(blank=True, help_text='Thời gian offline (giây)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='livelocation',
            new_name='tracking_li_worker__588f2f_idx',
            old_name='tracking_worker_last_idx',
        ),
        migrations.RenameIndex(
            model_name='livelocation',
            new_name='tracking_li_task_id_18efa6_idx',
            old_name='tracking_task_idx',
        ),
        migrations.RenameIndex(
            model_name='locationconsent',
            new_name='tracking_lo_worker__38ff29_idx',
            old_name='tracking_worker_consent_idx',
        ),
        migrations.RenameIndex(
            model_name='locationhistory',
            new_name='tracking_lo_task_id_c61300_idx',
            old_name='tracking_task_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='locationhistory',
            new_name='tracking_lo_worker__da8ec1_idx',
            old_name='tracking_worker_recorded_idx',
        ),
        migrations.RenameIndex(
            model_name='sosalert',
            new_name='tracking_so_task_id_0b5b1b_idx',
            old_name='tracking_sos_task_status_idx',
        ),
        migrations.RenameIndex(
            model_name='sosalert',
            new_name='tracking_so_status_fce4df_idx',
            old_name='tracking_sos_status_created_idx',
        ),
        migrations.AddField(
            model_name='deviceheartbeat',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='device_heartbeat', to='core.task'),
        ),
        migrations.AddField(
            model_name='deviceheartbeat',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_heartbeats', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deviceofflinealert',
            name='heartbeat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tracking.deviceheartbeat'),
        ),
        migrations.AddField(
            model_name='deviceofflinealert',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_offline_alerts', to='core.task'),
        ),
        migrations.AddField(
            model_name='deviceofflinealert',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_offline_alerts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['device_status', 'last_seen'], name='tracking_de_device__1ec619_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceheartbeat',
            index=models.Index(fields=['worker', 'device_status'], name='tracking_de_worker__a15d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceofflinealert',
            index=models.Index(fields=['task', 'status'], name='tracking_de_task_id_43102d_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceofflinealert',
            index=models.Index(fields=['status', '-created_at'], name='tracking_de_status_b39d06_idx'),
        ),
        migrations.AddIndex(
            model_name='deviceofflinealert',
            index=models.Index(fields=['worker', 'status'], name='tracking_de_worker__db061f_idx'),
        ),
    ]
