# Generated by Django 5.2.15 on 2026-08-13 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_verification_pin_hash_and_more'),
        ('tracking', '0002_deviceheartbeat_deviceofflinealert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomVerificationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, help_text='Thời điểm hệ thống bất ngờ chọn để yêu cầu xác minh')),
                ('respond_deadline', models.DateTimeField(help_text='Hạn chót phản hồi, ví dụ triggered_at + 90s')),
                ('status', models.CharField(choices=[('pending', 'Đang chờ CarePartner phản hồi'), ('confirmed', 'CarePartner nhập đúng mã trong thời hạn'), ('wrong_code', 'CarePartner nhập sai mã'), ('timeout', 'Hết thời gian, CarePartner không phản hồi')], db_index=True, default='pending', max_length=20)),
                ('attempts', models.IntegerField(default=0, help_text='Số lần nhập sai')),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('response_lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('response_lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('push_sent', models.BooleanField(default=False, help_text='Đã gửi push yêu cầu xác minh')),
                ('push_retry_count', models.IntegerField(default=0, help_text='Số lần đã retry push')),
            ],
            options={
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.AddField(
            model_name='deviceofflinealert',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, help_text='Parent đã xem/acknowledge alert', null=True),
        ),
        migrations.AddField(
            model_name='deviceofflinealert',
            name='push_retry_count',
            field=models.IntegerField(default=0, help_text='Số lần đã retry push'),
        ),
        migrations.AddIndex(
            model_name='deviceofflinealert',
            index=models.Index(fields=['status', 'acknowledged_at', 'push_sent_at'], name='tracking_de_status_1bd455_idx'),
        ),
        migrations.AddField(
            model_name='randomverificationcheck',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to='core.task'),
        ),
        migrations.AddField(
            model_name='randomverificationcheck',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_checks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='randomverificationcheck',
            index=models.Index(fields=['task', 'status'], name='tracking_ra_task_id_f65511_idx'),
        ),
        migrations.AddIndex(
            model_name='randomverificationcheck',
            index=models.Index(fields=['worker', 'status'], name='tracking_ra_worker__277069_idx'),
        ),
        migrations.AddIndex(
            model_name='randomverificationcheck',
            index=models.Index(fields=['status', 'respond_deadline'], name='tracking_ra_status_f37bc2_idx'),
        ),
    ]
