# Generated by Django 5.2.15 on 2026-08-13 08:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_user_verification_pin_hash_and_more'),
        ('tracking', '0003_randomverificationcheck_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='locationhistory',
            name='client_recorded_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Timestamp client ghi nhận GPS (cho batch offline sync). NULL nếu gửi real-time.', null=True),
        ),
        migrations.AddIndex(
            model_name='locationhistory',
            index=models.Index(fields=['task', 'client_recorded_at'], name='tracking_lo_task_id_e925c3_idx'),
        ),
    ]
