# Generated by Django 5.2.15 on 2026-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_qa_fix_2_idempotent_batch_and_constraints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deviceheartbeat',
            name='device_status',
            field=models.CharField(choices=[('online', 'Trực tuyến — đang gửi heartbeat'), ('offline', 'Ngoại tuyến — không nhận heartbeat > TRACKING_OFFLINE_THRESHOLD'), ('stopped', 'Đã dừng — task hoàn thành/huỷ')], db_index=True, default='online', max_length=20),
        ),
        migrations.AlterField(
            model_name='randomverificationcheck',
            name='respond_deadline',
            field=models.DateTimeField(help_text='Hạn chót phản hồi, ví dụ triggered_at + RESPOND_TIMEOUT_SECONDS'),
        ),
    ]
