# Generated by Django 5.2.15 on 2026-08-13 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0007_alter_deviceheartbeat_device_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, help_text='Thời điểm scheduler chạy lần gần nhất (UTC). NULL nếu scheduler chưa chạy lần nào.', null=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='Thời điểm bắt đầu lần chạy (UTC).', null=True)),
                ('finished_at', models.DateTimeField(blank=True, help_text='Thời điểm kết thúc lần chạy (UTC).', null=True)),
                ('source', models.CharField(default='cron', help_text='Process nào ghi: cron/daemon/web_worker/test.', max_length=20)),
                ('scheduler_kind', models.CharField(choices=[('both', 'Cả offline + verification'), ('offline', 'Chỉ offline check'), ('verification', 'Chỉ verification check'), ('unknown', 'Không xác định')], default='both', help_text='Scheduler nào chạy: both/offline/verification.', max_length=20)),
                ('success', models.BooleanField(default=True, help_text='True nếu chạy không exception. False nếu có error.')),
                ('error_message', models.TextField(blank=True, default='', help_text='Exception message nếu success=False.')),
                ('stats', models.JSONField(blank=True, default=dict, help_text='Stats dict trả về từ offline_scheduler/verification_scheduler.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Scheduler health',
                'ordering': ['-last_run_at'],
            },
        ),
    ]
