# Generated by Django 5.2.15 on 2026-08-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_qa_fix_6_livelocation_client_recorded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomverificationcheck',
            name='parent_photo_notification_sent',
            field=models.BooleanField(default=False, help_text="B5: đã gửi thông báo 'ảnh đã nộp' cho phụ huynh chưa (1 lần/check)."),
        ),
        migrations.AddField(
            model_name='randomverificationcheck',
            name='photo',
            field=models.ImageField(blank=True, help_text='B5: ảnh xác minh CarePartner chụp tại chỗ.', null=True, upload_to='verification_photos/'),
        ),
        migrations.AddField(
            model_name='randomverificationcheck',
            name='photo_submitted_at',
            field=models.DateTimeField(blank=True, help_text="B5: thời điểm ảnh hợp lệ được nộp (check chuyển 'confirmed').", null=True),
        ),
        migrations.AddField(
            model_name='randomverificationcheck',
            name='verification_type',
            field=models.CharField(choices=[('pin', 'Nhập mã PIN cá nhân'), ('photo', 'Chụp ảnh xác minh tại chỗ')], db_index=True, default='pin', help_text="B5: loại xác minh — 'pin' (nhập mã) hoặc 'photo' (chụp ảnh).", max_length=10),
        ),
    ]
