# Generated by Django 5.2.15 on 2026-08-23 08:03

import tracking.storages
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_b5_photo_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomverificationcheck',
            name='photo',
            field=models.ImageField(blank=True, help_text='B5: ảnh xác minh CarePartner chụp tại chỗ (lưu ngoài MEDIA_ROOT — không public).', null=True, storage=tracking.storages.PrivateVerificationPhotoStorage, upload_to='verification_photos/'),
        ),
    ]
