# Generated by SAFETY-LOC-001 fix
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_b5_photo_private_storage'),
    ]

    operations = [
        # 1. Thêm location_permission_status vào DeviceHeartbeat
        migrations.AddField(
            model_name='deviceheartbeat',
            name='location_permission_status',
            field=models.CharField(
                default='unknown',
                max_length=10,
                help_text='Trạng thái quyền vị trí trên thiết bị: granted/denied/unknown',
            ),
        ),
        # 2. Thêm alert_type vào DeviceOfflineAlert
        #    Default 'device_offline' để dữ liệu hiện có không bị ảnh hưởng.
        migrations.AddField(
            model_name='deviceofflinealert',
            name='alert_type',
            field=models.CharField(
                choices=[
                    ('device_offline', 'Mất kết nối thiết bị (mạng/tắt máy/gỡ app)'),
                    ('location_permission_revoked', 'Carepartner tắt quyền vị trí/GPS'),
                ],
                default='device_offline',
                max_length=35,
                db_index=True,
                help_text='Loại cảnh báo: device_offline hoặc location_permission_revoked',
            ),
        ),
        # 3. Thêm index cho alert_type + status
        migrations.AddIndex(
            model_name='deviceofflinealert',
            index=models.Index(fields=['alert_type', 'status'], name='tracking_aler_alert_type__idx'),
        ),
    ]
